### ISSUE TITLE
Display nothing with chrome/firefox in Macbook

### ISSUE THREAD

**Issue by yacloud** [shimberger/gohls#13]
Hi, i just followed the [guide](https://github.com/shimberger/gohls#running-it) to setup an environment, all works fine but it doesn't work with chrome or firefox, only works in Safari. Besides the cpu consumption is high?  is that a normal phenomenon? 

>macOS 10.12.1
>Chrome:  54.0.2840.98 (64-bit)
>firefox 45.5.1
>safari: Version 10.0.1 (12602.2.14.0.7)

**Comment by shimberger** [comment]
@yacloud The CPU usage is high.. that is unfortunately normal for now. I hope #11 will help.

I suspect with showing nothing you mean the videos and not the list pages? Then this is normal at this point because Chrome and firefox don't support HTTP live streaming (HLS) out of the box and I haven't gotten it to work with javascript or VLC. See issue #4 

I hope I can fix it this year. 

Thanks so much for the report!

**Comment by shimberger** [comment]
@yacloud I finally fixed playback in Chrome and Firefox. I created a new release so feel free to try it out. The CPU usage is still high. I'm gonna work on it next once I get some free time. I'm gonna close this issue but feel free to follow #15 if you're interested in better performance.
