### ISSUE TITLE
Unable to build the application for Development.

### ISSUE THREAD

**Issue by MaruthiVSM** [shimberger/gohls#41]
I downloaded the code as per instructions and did:
./scripts/run.sh

I get the below error:
internal/api/assets.go:2: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
# github.com/shimberger/gohls/internal/fileindex
internal/fileindex/index_mem.go:191:2: undefined: logrus.Tracef

**Comment by shimberger** [comment]
@MaruthiVSM I will have to check this out next week, since I am out of town. Sorry. I think there might be a new version of logrus. kicked off a CI job to see if it also happens there. If not it might be an issue for you locally? Which OS are you building it on? 

https://circleci.com/gh/shimberger/gohls/70

**Comment by shimberger** [comment]
@MaruthiVSM The instructions were actually old. I updated the instructions. Do you care to try again?

**Comment by renguifeng** [comment]
how can I  get  the video list  from  php file_get_contents

**Comment by renguifeng** [comment]
I want  to show  one video on the other web page，so  I want  to get the  video url ，how can  I  do ，thanks！

**Comment by shimberger** [comment]
@MaruthiVSM I'm closing this to clean up tickets. Please re-open if you want to chat again.
