### ISSUE TITLE
Playback broken on some files

### ISSUE THREAD

**Issue by midzer** [shimberger/gohls#61]
Hi,

while using current master code in development I reconed some files do no play properly:

Basically `video.js` is throwing an error. After a long time of research (and moving to `hls.js` meanwhile) I figured out it is because of our ffmpeg audio encoding.

I managed to fix it and want to show it to you in a PR. Is that okay?

Cheers
midzer

**Comment by shimberger** [comment]
Hey midzer,

that is awesome! Thanks so much! I was looking at hls.js and if you've made some progress a PR is very welcome :). I basically approve most PRs because this was a hobby projects that got more feedback then I ever anticipated (I basically wrote it to write some go and learn about video encoding).
