### ISSUE TITLE
Support archives

### ISSUE THREAD

**Issue by midzer** [shimberger/gohls#64]
Hello,

I think it would be awesome if gohls can look into non-compressed archives (zip/rar) as well and do ffmpeg with its video on the fly.

What do you think about that?

Cya
midzer

**Comment by shimberger** [comment]
Thanks for the Idea :) It sounds like a cool feature but I am not sure how to implement it. I suspect it would make the code quite complex since right now we are calling ffmpeg with a filename and capturing stdout for encoding. I guess we would have to temporarily unpack the files but then we are using the space anyway and the idea of using archives almost seems moot.

If you have a good way to implement it, let me know. In general I am happy to accept all kinds of PRs if someone finds it useful but this one sounds like it could make things complicated.

**Comment by midzer** [comment]
I did some investigation. Maybe https://github.com/mholt/archiver does the trick:

> Stream files in and out of archives without needing actual files on disk

**Comment by shimberger** [comment]
Thanks for all the research. I am not sure it is feasible to stream into ffpmeg since AFAIK ffmpeg needs to seek around the file to find the position and it can't do that with a stream. Are you willing to do an experiment? What's the use case? Do you have uncompressed media that is stored in archives? I don't want to discourage you I am just not sure it won't make things more complicated.

**Comment by shimberger** [comment]
I'm closing this issue for now but put it in the idea-backlog.
