### ISSUE TITLE
A note of thank you and a request.

### ISSUE THREAD

**Issue by blmhemu** [shimberger/gohls#68]
First of all, **thank you** for this amazing project. It is really elegant and informative especially about hls with ffmpeg. I was searching relentlessly on how to generate good (equal spaced) hls streams using ffmpeg. There is very little information on the web and the ffmpeg docs can be intimidating to a newbie. I have read through gohls source code and found answers to many questions.

**Coming to the feature requests / improvements :**
1. I see that 720p is hardcoded as default resolution. This can be probably be solved by following [this](https://docs.peer5.com/guides/production-ready-hls-vod/) guide along with a small change in parsing the api path.

2. Also I was wondering if [dash](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) could be implemented.

Please feel free to update the title as required.

**Comment by shimberger** [comment]
@blmhemu Sorry for the late reply and thank you so much for the kind words. Yes, understanding HLS and video encoding in general was why I started this project in the first place. It was more of a learning opportunity and I never expected anyone to use it.

Regarding different resolutions: Yes, that should be pretty straighforward. Do you want to take a swing at it? I am planning on spending a bit of time coding on the weekends but otherwise my time is limited to if you want to give it a try, feel free to go ahead 👍 

Regarding dash: I suspect that would work somehow but I am not (yet) familiar with dash. I'd be open to PRs though.

**Comment by blmhemu** [comment]
I have actually implemented it in a rust fork. It is not even halfway though.
https://github.com/blmhemu/rumble

**Comment by vgarleanu** [comment]
Getting on-demand streaming with dash works except seeking to non-transcoded timestamps is quite difficult because of continuity issues between the segments. Most native video players seem to ignore the continuity issues but libs like video.js crash when seeking to a non-transcoded region.
The only way i got it work was to reload the manifest with a few changes in it, this in turn reloads the initialization segment and playback continues.

**Comment by shimberger** [comment]
I'm closing this issue since I won't have time to implement dash.

The streaming quality is already covered by: #51
